// Code generated by entc, DO NOT EDIT.

package ent

import (
	"GoBabel/Common/ent/call"
	"GoBabel/Common/ent/conference"
	"GoBabel/Common/ent/predicate"
	"context"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// CallUpdate is the builder for updating Call entities.
type CallUpdate struct {
	config
	hooks      []Hook
	mutation   *CallMutation
	predicates []predicate.Call
}

// Where adds a new predicate for the builder.
func (cu *CallUpdate) Where(ps ...predicate.Call) *CallUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetStartedAt sets the started_at field.
func (cu *CallUpdate) SetStartedAt(t time.Time) *CallUpdate {
	cu.mutation.SetStartedAt(t)
	return cu
}

// SetFinishedAt sets the finished_at field.
func (cu *CallUpdate) SetFinishedAt(t time.Time) *CallUpdate {
	cu.mutation.SetFinishedAt(t)
	return cu
}

// AddConferenceIDs adds the conference edge to Conference by ids.
func (cu *CallUpdate) AddConferenceIDs(ids ...int) *CallUpdate {
	cu.mutation.AddConferenceIDs(ids...)
	return cu
}

// AddConference adds the conference edges to Conference.
func (cu *CallUpdate) AddConference(c ...*Conference) *CallUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddConferenceIDs(ids...)
}

// Mutation returns the CallMutation object of the builder.
func (cu *CallUpdate) Mutation() *CallMutation {
	return cu.mutation
}

// RemoveConferenceIDs removes the conference edge to Conference by ids.
func (cu *CallUpdate) RemoveConferenceIDs(ids ...int) *CallUpdate {
	cu.mutation.RemoveConferenceIDs(ids...)
	return cu
}

// RemoveConference removes conference edges to Conference.
func (cu *CallUpdate) RemoveConference(c ...*Conference) *CallUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveConferenceIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CallUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CallMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CallUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CallUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CallUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CallUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   call.Table,
			Columns: call.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: call.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.StartedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: call.FieldStartedAt,
		})
	}
	if value, ok := cu.mutation.FinishedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: call.FieldFinishedAt,
		})
	}
	if nodes := cu.mutation.RemovedConferenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   call.ConferenceTable,
			Columns: call.ConferencePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: conference.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ConferenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   call.ConferenceTable,
			Columns: call.ConferencePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: conference.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CallUpdateOne is the builder for updating a single Call entity.
type CallUpdateOne struct {
	config
	hooks    []Hook
	mutation *CallMutation
}

// SetStartedAt sets the started_at field.
func (cuo *CallUpdateOne) SetStartedAt(t time.Time) *CallUpdateOne {
	cuo.mutation.SetStartedAt(t)
	return cuo
}

// SetFinishedAt sets the finished_at field.
func (cuo *CallUpdateOne) SetFinishedAt(t time.Time) *CallUpdateOne {
	cuo.mutation.SetFinishedAt(t)
	return cuo
}

// AddConferenceIDs adds the conference edge to Conference by ids.
func (cuo *CallUpdateOne) AddConferenceIDs(ids ...int) *CallUpdateOne {
	cuo.mutation.AddConferenceIDs(ids...)
	return cuo
}

// AddConference adds the conference edges to Conference.
func (cuo *CallUpdateOne) AddConference(c ...*Conference) *CallUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddConferenceIDs(ids...)
}

// Mutation returns the CallMutation object of the builder.
func (cuo *CallUpdateOne) Mutation() *CallMutation {
	return cuo.mutation
}

// RemoveConferenceIDs removes the conference edge to Conference by ids.
func (cuo *CallUpdateOne) RemoveConferenceIDs(ids ...int) *CallUpdateOne {
	cuo.mutation.RemoveConferenceIDs(ids...)
	return cuo
}

// RemoveConference removes conference edges to Conference.
func (cuo *CallUpdateOne) RemoveConference(c ...*Conference) *CallUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveConferenceIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *CallUpdateOne) Save(ctx context.Context) (*Call, error) {

	var (
		err  error
		node *Call
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CallMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CallUpdateOne) SaveX(ctx context.Context) *Call {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *CallUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CallUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CallUpdateOne) sqlSave(ctx context.Context) (c *Call, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   call.Table,
			Columns: call.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: call.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Call.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.StartedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: call.FieldStartedAt,
		})
	}
	if value, ok := cuo.mutation.FinishedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: call.FieldFinishedAt,
		})
	}
	if nodes := cuo.mutation.RemovedConferenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   call.ConferenceTable,
			Columns: call.ConferencePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: conference.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ConferenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   call.ConferenceTable,
			Columns: call.ConferencePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: conference.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Call{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{call.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
