name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade conan
        run: pip install conan --upgrade

      - name: Install libs
        run: make mouli-install

      - name: Build binaries
        run: make re

      - name: Unit Tests
        run: make tests_run
